<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FEPQ0C3" ignored="0" name="RerunTestcase" tests="9" failures="2" timestamp="2022-10-08T14:11:47 IST" time="0.137" errors="0">
  <testcase name="test3" time="0.018" classname="com.prac.failedtestcase.TestClass3">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.005" classname="com.prac.failedtestcase.TestClass3">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.005" classname="com.prac.failedtestcase.TestClass3">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test3" time="0.005" classname="com.prac.failedtestcase.TestClass3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.prac.failedtestcase.TestClass3.test3(TestClass3.java:12)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.002" classname="com.prac.failedtestcase.TestClass2">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.003" classname="com.prac.failedtestcase.TestClass2">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="com.prac.failedtestcase.TestClass2">
    <skipped/>
  </testcase> <!-- test2 -->
  <testcase name="test2" time="0.002" classname="com.prac.failedtestcase.TestClass2">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.prac.failedtestcase.TestClass2.test2(TestClass2.java:12)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test1" time="0.005" classname="com.prac.failedtestcase.TestClass1"/>
</testsuite> <!-- RerunTestcase -->
