<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-FEPQ0C3" ignored="0" name="Test" tests="2" failures="1" timestamp="2022-10-08T23:01:18 IST" time="0.032" errors="0">
  <testcase name="testMethod01_smoke" time="0.004" classname="listenersmoke.DemoSmoke">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
at listenersmoke.DemoSmoke.testMethod01_smoke(DemoSmoke.java:11)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 35 stack frames]]>
    </failure>
  </testcase> <!-- testMethod01_smoke -->
  <testcase name="testMethod02_smoke" time="0.004" classname="listenersmoke.DemoSmoke"/>
</testsuite> <!-- Test -->
